build site:
	image: node:6
	state: build
	script:
		- npm install --progress=false
		- npm run build
	artivacts:
		expire_in: 1 week
		paths:
			- dist

unit test:
	image: node:6
	state: test
	script:
		- npm install --progress=false
		- npm run unit

deploy:
	image: alpine
	state: deploy
	script:
		- apk add --no-cache rsync openssh
		- mkdir -p ~/.ssh
		- echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
		- chmod 600 ~/.ssh/id_dsa
		- echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
		- rsync -rav --delete dist/ user@server.com:/your/project/path/